config/routes.rb
SocialSpin::Application.routes.draw do
  get 'profiles/show'

  devise_for :users

  match '/rate' => 'rater#create', :as => 'rate'

  get "songs/index"

  get "albums/index"

  get "artists/index"

  resources :media

  get "home/index"

  get 'media/show'

  get "contact/contact"

  get "media/index"
  
  match 'users/:id' => 'profiles#show'

   root :to => 'home#index'

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  helper_method :show

  # GET /media
  # GET /media.json
  def index
    @search = Medium.search do
      fulltext params[:search]
    end
    @media = @search.results
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @media }
    end
  end

  # GET /media/1
  # GET /media/1.json
  def show
    @medium = Medium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medium }
    end
  end

  # GET /media/new
  # GET /media/new.json
  def new
    @medium = Medium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medium }
    end
  end

  # GET /media/1/edit
  def edit
    @medium = Medium.find(params[:id])
  end

  # POST /media
  # POST /media.json
  def create
    @medium = Medium.new(params[:medium])

    respond_to do |format|
      if @medium.save
        format.html { redirect_to @medium, notice: 'Media was successfully created.' }
        format.json { render json: @medium, status: :created, location: @medium }
      else
        format.html { render action: "new" }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /media/1
  # PUT /media/1.json
  def update
    @medium = Medium.find(params[:id])

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to @medium, notice: 'Media was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media/1
  # DELETE /media/1.json
  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to media_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/media_helper.rb
module MediaHelper
end

app/views/media/_form.html.erb
<%= simple_form_for @medium, :html => {:multipart => true} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :artist %>
    <%= f.input :artist_description %>
    <%= f.input :album %>
    <%= f.input :album_description %>
    <%= f.input :year %>
    <%= f.input :average_rating %>
    <%= f.file_field :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/media/edit.html.erb
<h1>Editing media</h1>

<%= render 'form' %>

<%= link_to 'Show', @medium %> |
<%= link_to 'Back', media_path %>

app/views/media/index.html.erb
<h1>Listing media</h1>

<table>
  <tr>
    <th>Artist</th>
    <th>Artist description</th>
    <th>Album</th>
    <th>Album description</th>
    <th>Year</th>
    <th>Average rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @media.each do |medium| %>
  <tr>
    <td><%= medium.artist %></td>
    <td><%= medium.artist_description %></td>
    <td><%= medium.album %></td>
    <td><%= medium.album_description %></td>
    <td><%= medium.year %></td>
    <td><%= medium.average_rating %></td>
    <td><%= link_to 'Show', medium %></td>
    <td><%= link_to 'Edit', edit_medium_path(medium) %></td>
    <td><%= link_to 'Destroy', medium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />




<%= link_to 'New Media', new_medium_path %>

app/views/media/new.html.erb
<h1>New media</h1>

<%= render 'form' %>

<%= link_to 'Back', media_path %>

app/views/media/show.html.erb
<p id="notice"><%= notice %></p>


<h3><%= @medium.artist %></h3>
<div class="media">
<div class="pull-left">
  <%= image_tag @medium.image_url.to_s, "class" => "media-object", "data-src" => "holder.js/300x200" %>
</div>

<p>
  <b>Artist description:</b>
  <%= @medium.artist_description %>
</p>

<p>
  <b>Album:</b>
  <%= @medium.album %>
</p>

<p>
  <b>Album description:</b>
  <%= @medium.album_description %>
</p>

<p>
  <b>Year:</b>
  <%= @medium.year %>
</p>

<p>
  <h4>Rate Artist :</h4> <%= rating_for @medium, "artist" %>
</p>
</div>