config/routes.rb
SocialSpin::Application.routes.draw do
  get 'profiles/show'

  devise_for :users

  match '/rate' => 'rater#create', :as => 'rate'

  get "songs/index"

  get "albums/index"

  get "artists/index"

  resources :media

  get "home/index"

  get 'media/show'

  get "contact/contact"

  get "media/index"
  
  match 'users/:id' => 'profiles#show'

   root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialSpin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner" style="width: auto; padding: 0 20px;">
			<a class="brand" href="/home/index.html">Social Spin <%=image_tag("logo.png", alt: "Albums Image")%> Be Heard</a>
			<form class="form-inline">
					<ul class="nav pull-right">
						
						<% if user_signed_in? %>
							<li><%= link_to current_user.first_name, profiles_show_path %></li>
							<li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
						<% else %>
							<li><%= link_to "Sign In", user_session_path  %></li>
							<li><%= link_to "Register", new_user_registration_path  %></li>
						<% end %>
											
					</ul>
				</form>
		</div>
		
	</div>
	
	<div class="container">	
		<div class="row">
			<div class="span3">
				<ul class="nav nav-list" data-spy="affix">
					<li><a href="/home/index.html"><%=image_tag("home.png", alt: "Example Image")%><br />Home</a></li>
					<li><a href="/artists/index.html"><%=image_tag("artists.png", alt: "Example Image")%><br />Artists</a></li>
					<li><a href="/songs/index.html"><%=image_tag("songs.png", alt: "Example Image")%><br />Songs</a></li>
					<li><a href="/albums/index.html"><%=image_tag("albums.png", alt: "Example Image")%><br />Albums</a></li>
					<li><a href="/contact/contact.html"><%=image_tag("contact.png", alt: "Example Image")%><br />Contact</a></li>
				</ul>
			</div>
			<div class="span9">
				<%= yield %>
				

			</div>
		</div>	
	</div>
	<div class="navbar navbar-fixed-bottom navbar-inverse">
		<div class="navbar-inner">
	  		<ul class="nav">
	  			<li><a href="mailto:dillonlara115@gmail.com?Subject=Social%20Spin">Contact Dillon Lara at dillonlara115@gmail.com for any questions</a></li>
	  		</ul>
	  	</div>
	</div>
</body>
</html>